### ISSUE TITLE
'$' is not defined

### ISSUE THREAD

**Issue by pzehle** [Revln9/react-cornerstone#1]
Hello,

I am starting a new project where I need to use cornerstone.js. I found your repository and downloaded it. I imported the module and I get the next error:

```
./src/libs/cornerstone/cornerstone2.js
  Line 593:  '$' is not defined  no-undef
  Line 597:  '$' is not defined  no-undef
```

Could you please help solve this?

Thanks!

**Comment by pzehle** [comment]
Nevermind, I just deleted the remaining jQuery references.

**Comment by Revln9** [comment]
Hi pablo , my advice would be to reinstall cornerstone core `npm install cornerstone-core` because i made this repo , back when cornerstone used jquery as a dependency , now cornerstone core is completely decoupled from jquery. there's no point in using the library included in this repo anymore , updates are coming soon. Hope it helps !

**Comment by pzehle** [comment]
Hi! Thanks for your answer and advice. As a matter of fact, I am trying to use the cornerstone-core as you suggested. Just starting, I get this error, do you have any idea if I need any further configuration?

```
loadImageFromImageLoader: no image loader for imageId

cornerstone.loadImage(imageId).then(function(image) {
	var viewport = cornerstone.getDefaultViewport(element.children[0], image);
	cornerstone.displayImage(element, image , viewport);
 });
```

Thanks!!

**Comment by pzehle** [comment]
Hi. For what is worth, I got it working installing with NPM also `cornerstone-wado-image-loader`.

Thanks again for everything and I am looking forward for your new repo with all this changes. :)
